<font size="2">Please enter the user information</font>
<hr>
<p><form method="post" action="incs/adduser.php" name="adduser" autocomplete="off">
<!-- <input name="realname" value="Real Name">Full Name<br> -->
 <input name="username" value="Enter Username"> Username<br>
 <input name="password" type="password"> Password<br>
 <input name="password1" type="password"> Password<br>
 <input name="email" value="Email Address"> Email Address<br>
 <input type="submit" value="Submit User Info" name="submit">
</form>

