<div class="menu"> 
<select name="page" id="page" onchange="window.location=this.value;">
  <option>Choose one...</option> 
  <option value="main.php">- Main Page</option>
  <option value="">- Project Management</option>
  <option value="createproj.php">-- Create New Project</option>
  <option value="">-- View Projects</option>
  <option value="">- Import XML Data</option>
  <option value="">-- Import Nessus XML</option>
  <option value="">-- Import Nexpose XML</option>
  <option value="search.php">- Vulnerability Search</option>
  <option value="index.php">-Risk Assessments</option>
  <option value="pci.php">-- PCI-DSS</option>
  <option value="80053.php">-- NIST 800-53a</option>
  <option value="hipaa.php">-- HIPAA</option>
  <option value="iso.php">-- ISO27000</option>
  <option value="">- User Administration</optiom>
  <option value="userinfo.php">-- Add User</option>
  <option value="deluser.php">-- Delete User</option>
  <option value="moduser.php">-- Modify user</option>
  <option value="about.php">- About VA/PT</option>
</select>&nbsp Menu Options 
</div>
