<div class="menu"> 
<select name="page" id="page" onchange="window.location=this.value;">
  <option>Choose one...</option> 
  <option value="index.php">Home Page</option>
  <option value="index.php">User Administration</optiom>
  <option value="userinfo.php">-- Add User</option>
  <option value="deluser.php">-- Delete User</option>
  <option value="moduser.php">-- Modify user</option>
  <option value="search.php">Vulnerability Search</option>
  <option value="index.php">Risk Assessments</option>
  <option value="pci.php">-- PCI-DSS</option>
  <option value="80053.php">-- NIST 800-53a</option>
  <option value="hipaa.php">-- HIPAA</option>
  <option value="iso.php">-- ISO27000</option>
</select>&nbsp Menu Options 
</div>
