<div class="menu"> 
<select name="page" id="page" onchange="window.location=this.value;">
  <option>Choose one...</option> 
  <option value="main.php">- Main Page</option>
  <option value="">- Project Management</option>
  <option value="createproj.php">-- Create New Project</option>
  <option value="viewproj.php">-- View Projects</option>
  <option value="">- Import CSV/XML Data</option>
  <option value="upload.php">-- Import Nessus CSV</option>
  <option value="upload.php">-- Import Nmap XML</option>
  <option value="upload.php">-- Import w3af CSV</option>
  <option value="search.php">- Vulnerability Search</option>
  <option value="">-Risk Assessments</option>
  <option value="pci.php">-- PCI-DSS</option>
  <option value="">-- NIST 800-53a</option>
  <option value="">-- HIPAA</option>
  <option value="">-- ISO27000</option>
  <option value="">- User Administration</optiom>
  <option value="userinfo.php">-- Add User</option>
  <option value="deluser.php">-- Delete User</option>
  <option value="">-- Modify User</option>
</select>&nbsp Menu Options 
</div>
